providers:
  docker: {}

entryPoints:
  web:
    address: ":80"
    http:
     redirections:
       entrypoint:
         to: websecure
         scheme: https

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: schrom@gmx.de
      storage: acme.json
      httpChallenge:
        entryPoint: web
        #      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
